import { MIN_PLAN_WEEKS, type PlanDay, type PlanSettings, type PlanWeek, raceLabel } from "./plan-types";
import { formatPace, getWorkoutPace, parsePace } from "./running";

/**
 * Port of v1's `generateDefaultPlan()` — same phase allocation, same distance
 * ramps, same notes, so a plan generated here is indistinguishable from one
 * generated by the legacy app.
 */
export function generateDefaultPlan(
	numWeeks: number,
	settings: Pick<PlanSettings, "raceDistance" | "targetPace">,
): PlanWeek[] {
	const weeks = Math.max(numWeeks, MIN_PLAN_WEEKS);
	const plan: PlanWeek[] = [];
	const raceDist = settings.raceDistance;
	const label = raceLabel(raceDist);

	// Scale distances relative to race distance (base: half marathon = 21.1)
	const scale = raceDist / 21.1;
	const sc = (km: number) => Math.round(km * scale * 10) / 10;

	// Allocate phases proportionally
	const raceWeeks = 1;
	const remaining = weeks - raceWeeks;
	const taperWeeks = Math.max(1, Math.round(remaining * 0.1));
	const baseWeeks = Math.max(2, Math.round(remaining * 0.3));
	const peakWeeks = Math.max(1, Math.round(remaining * 0.25));
	const buildWeeks = Math.max(1, remaining - baseWeeks - peakWeeks - taperWeeks);

	// Peak long run: ~90% of race distance
	const peakLong = Math.round(raceDist * 0.9 * 10) / 10;

	let w = 1;
	const lerp = (min: number, max: number, t: number) => Math.round((min + (max - min) * t) * 10) / 10;

	// BASE BUILDING: 3 runs/week
	for (let i = 0; i < baseWeeks; i++) {
		const t = baseWeeks === 1 ? 1 : i / (baseWeeks - 1);
		const long = lerp(sc(3), sc(8), t);
		const easy = lerp(sc(2), sc(3.5), t);
		plan.push({
			week: w++,
			phase: "Base Building",
			days: [
				{ day: "Tue", type: "Easy Run", distance: easy, notes: "Comfortable pace, conversational" },
				{ day: "Thu", type: "Easy Run", distance: easy, notes: "Comfortable pace" },
				{ day: "Sun", type: "Long Run", distance: long, notes: "Slow and steady, build endurance" },
			],
		});
	}

	// BUILDING VOLUME: 4 runs/week, add quality sessions
	for (let i = 0; i < buildWeeks; i++) {
		const t = buildWeeks === 1 ? 1 : i / (buildWeeks - 1);
		const long = lerp(sc(9), sc(14), t);
		const easy = lerp(sc(4), sc(5), t);
		const qualDist = lerp(sc(4), sc(6), t);
		const isInterval = i % 2 === 1;
		plan.push({
			week: w++,
			phase: "Building Volume",
			days: [
				{ day: "Tue", type: "Easy Run", distance: easy, notes: "Comfortable pace" },
				{
					day: "Wed",
					type: isInterval ? "Intervals" : "Tempo Run",
					distance: qualDist,
					notes: isInterval
						? `${Math.round(3 + t * 3)}×800m fast with 400m jog recovery`
						: `10 min warm-up, ${Math.round(15 + t * 15)} min tempo, 10 min cool-down`,
				},
				{ day: "Fri", type: "Easy Run", distance: lerp(sc(3), sc(4.5), t), notes: "Recovery pace" },
				{ day: "Sun", type: "Long Run", distance: long, notes: "Steady, controlled effort" },
			],
		});
	}

	// PEAK TRAINING: 4 runs/week, long run builds to ~90% race distance
	for (let i = 0; i < peakWeeks; i++) {
		const t = peakWeeks === 1 ? 1 : i / (peakWeeks - 1);
		const long = lerp(sc(15), peakLong, t);
		const easy = lerp(sc(5), sc(6), t);
		const qualDist = lerp(sc(6), sc(8), t);
		const types = ["Race Pace", "Tempo Run", "Intervals"];
		const qType = types[i % 3];
		const notes =
			qType === "Race Pace"
				? `2km warm-up, ${Math.round(3 + t * 3)}km at race pace, 1km cool-down`
				: qType === "Intervals"
					? `${Math.round(4 + t * 2)}×800m at race pace with 400m jog`
					: `10 min warm-up, ${Math.round(25 + t * 10)} min tempo, 10 min cool-down`;
		plan.push({
			week: w++,
			phase: "Peak Training",
			days: [
				{ day: "Tue", type: "Easy Run", distance: easy, notes: "Keep it easy" },
				{ day: "Wed", type: qType, distance: qualDist, notes },
				{ day: "Fri", type: "Easy Run", distance: lerp(sc(4), sc(5.5), t), notes: "Recovery pace" },
				{ day: "Sun", type: "Long Run", distance: long, notes: "Build mental toughness, stay relaxed" },
			],
		});
	}

	// TAPER: reduce volume progressively
	for (let i = 0; i < taperWeeks; i++) {
		const t = taperWeeks === 1 ? 1 : i / (taperWeeks - 1);
		const long = lerp(peakLong * 0.8, sc(8), t);
		const easy = lerp(sc(5), sc(3), t);
		plan.push({
			week: w++,
			phase: "Taper",
			days: [
				{ day: "Tue", type: "Easy Run", distance: easy, notes: "Relaxed effort" },
				{ day: "Thu", type: "Easy Run", distance: lerp(sc(4), sc(2), t), notes: "Short and easy" },
				{ day: "Sun", type: "Long Run", distance: long, notes: "Reduced volume, stay confident" },
			],
		});
	}

	// RACE WEEK
	plan.push({
		week: w++,
		phase: "Race Week!",
		days: [
			{ day: "Tue", type: "Easy Run", distance: Math.min(3, sc(3)), notes: "Light jog" },
			{ day: "Thu", type: "Shakeout", distance: 2, notes: "Very easy, a few strides" },
			{
				day: "Sun",
				type: "🏁 RACE DAY",
				distance: raceDist,
				notes: `${label}! Trust your training. Start easy, finish strong!`,
			},
		],
	});

	return applyTargetPace(plan, settings.targetPace);
}

/**
 * Stamps each workout with its suggested pace. v1 did this at generation time
 * and again whenever the target pace changed in Settings.
 */
export function applyTargetPace(weeks: PlanWeek[], targetPace: string): PlanWeek[] {
	const racePaceSec = parsePace(targetPace);
	return weeks.map((week) => ({
		...week,
		days: week.days.map((day) => {
			const paceSec = racePaceSec > 0 ? getWorkoutPace(day.type, racePaceSec) : 0;
			const next: PlanDay = { day: day.day, type: day.type, distance: day.distance, notes: day.notes };
			if (paceSec > 0) next.pace = formatPace(paceSec);
			return next;
		}),
	}));
}
